name: Gz Libs Jobs

# base_ref / head_reaf are only available in PRs
on: [workflow_dispatch, pull_request]

jobs:
  gz_libs_jobs:
    runs-on: ubuntu-latest
    name: Diff for DSL code
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Download and setup job dsl jar
        run: ./jenkins-scripts/dsl/tools/setup_local_generation.bash
      - name: Generate gz-libs files
        run: |
          cd jenkins-scripts/dsl
          WRITE_JOB_LOG=1 java -jar tools/jobdsl.jar gazebo_libs.dsl
          mv *.txt /tmp/current_log_generated/ || true
      - name: Archive job list
        uses: actions/upload-artifact@v3
        with:
          name: gz_libs_jobs
          path: /tmp/current_log_generated/jobs.txt
