name: Gz Libs Jobs

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'jenkins-scripts/dsl/*.dsl'
  push:
    branches:
      - master
    paths:
      - 'jenkins-scripts/dsl/*.dsl'

jobs:
  gz_libs_jobs:
    runs-on: ubuntu-latest
    name: Diff for DSL code
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Download and setup job dsl jar
        run: ./jenkins-scripts/dsl/tools/setup_local_generation.bash
      - name: Simulate token
        run: |
          sudo mkdir -p /var/lib/jenkins/ && sudo touch /var/lib/jenkins/remote_token
          sudo chown -R ${USER} /var/lib/jenkins
      - name: Generate gz-libs files
        run: |
          cd jenkins-scripts/dsl
          WRITE_JOB_LOG=1 java -jar tools/jobdsl.jar gazebo_libs.dsl
          # mkdir -p /tmp/current_log_generated
          # mv *.txt /tmp/current_log_generated/
      - name: Archive job list
        uses: actions/upload-artifact@v3
        with:
          name: gz_libs_jobs
          path: /tmp/current_log_generated/jobs.txt
      - name: Update file and push to remote
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add jenkins-scripts/dsl/jobs.txt
          git commit -m "Update jobs.txt"
          git push origin HEAD:${GITHUB_REF}
